# .travis.yml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

# This is YAML - indentation levels are crucial

language: cpp
compiler: gcc
dist: bionic

cache:
  directories:
  - $HOME/.cache

env:
  global:
    - SETUP_PATH=.ci-local:.ci
    - MODULES=gtest
    - GTEST=v1.0.0
    - BASE_HOOK=.ci-local/base.patch

addons:
  apt:
    packages:
    # for all EPICS builds
    - libreadline6-dev
    - libncurses5-dev
    - perl

install:
  - python .ci-local/install-sdk.py
  - python .ci/cue.py prepare

script:
  - python .ci/cue.py build
  - python .ci/cue.py test
  - python .ci/cue.py test-results

# Define build jobs

jobs:
  include:

  - env: BASE=7.0 UASDK=1.5.6
    dist: trusty

  - env: BASE=3.15 UASDK=1.5.6
    dist: trusty

  - env: BASE=R3.15.5 UASDK=1.5.6
    dist: trusty

  - env: BASE=7.0 UASDK=1.6.3
    compiler: gcc-6
    addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

  - env: BASE=3.15 UASDK=1.6.3
    compiler: gcc-6
    addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

  - env: BASE=R3.15.5 UASDK=1.6.3
    compiler: gcc-6
    addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

  - env: BASE=7.0 UASDK=1.7.2
    compiler: gcc-6
    addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

  - env: BASE=3.15 UASDK=1.7.2
    compiler: gcc-6
    addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

  - env: BASE=R3.15.5 UASDK=1.7.2
    compiler: gcc-6
    addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }
